comment:
  layout: "header, reach, diff, flags, components, files"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
        informational: true

  individual_components:
    - component_id: module_cmd  # this is an identifier that should not be changed
      name: cmd  # this is a display name, and can be changed freely
      paths:
        - cmd/ft_ping/**
