name: Docker Image Push

on:
  push:
    branches: [ "main" ]
    paths:
      - "Dockerfile"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/gawingowin/ft_ping_ci

    steps:
    - uses: actions/checkout@v4
    - name: Set short SHA
      id: var
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PUSH_KEY }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $IMAGE_NAME:${{ steps.var.outputs.SHORT_SHA }}
    - name: Push the Docker image
      run: docker push $IMAGE_NAME:${{ steps.var.outputs.SHORT_SHA }}